### ISSUE TITLE
Version SDL2

### ISSUE THREAD

**Issue by rchastain** [paul-maxime/merreles#1]
Bonjour !

Votre programme est un bijou (en toute sincérité).

J'en avais fait une version légèrement modifiée il y a un an, avec de nouvelles images.

Je viens de porter le programme vers SDL2 (ce qui m'a pris cinq minutes).

Si vous voulez y jeter un œil, le projet se trouve [ici](https://gitlab.com/rchastain/merelles).

Vous serez peut-être aussi intéressé par [cette discussion](https://www.developpez.net/forums/d2089226/autres-langages/pascal/representation-jeu-moulin/).

Bien cordialement.

Roland

**Comment by paul-maxime** [comment]
Hello !

Merci pour le compliment, je ne m'attendais pas à ce que ce projet réalisé il y a plus de 12 ans maintenant soit utilisé !
Comme quoi, il ne faut jamais hésiter à poster ses anciens projets sur GitHub. 😄 

Je viens de lire la discussion sur la représentation en mémoire, et dans mon cas j'ai clairement pris la solution de facilité, avec des gros tableaux en dur dans le code pour les positions et les intersections, comme vous avez sûrement pu voir :
https://github.com/paul-maxime/merreles/blob/master/src/field_move.c#L3
https://github.com/paul-maxime/merreles/blob/master/src/field_index.c#L3
Ce n'est clairement pas adapté à une IA performante qui doit parcourir rapidement l'arbre des coups possibles. 😓

Bon courage pour vos projets, c'est pas courant les gens qui connaissent ce jeu !
